### ISSUE TITLE
Unclear what process.argv.slice(2) is supposed to be

### ISSUE THREAD

**Issue by WinWinHost** [IOT-DSA/template-dslink-javascript#1]
I am trying to use this example, but I am not sure how I am supposed to connect to an EFF node.
Where is the connection configuration? 
What is being passed into the process.argv.slice(2)? 
Why don't you have a read me that explains how to use this?

**Comment by ghost** [comment]
If you don't provide an argument when you launch the example then it will default to using http://127.0.0.1:8080/conn as the broker address.

You can override this behaviour by providing an argument as below:-

node index.js --broker http://someotheraddress:8080/conn

As the Javascript SDK is just a wrapper of the DART one, I was able to gleem this from the DART SDK
